delete from editeur;
insert into editeur (nom, id_pays, infos) values ('Funk-Greenholt', 4, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into editeur (nom, id_pays, infos) values ('Lemke-Schmeler', 3, 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into editeur (nom, id_pays, infos) values ('Fay, Schowalter and Schaden', 1, 'Nulla mollis molestie lorem. Quisque ut erat.');
insert into editeur (nom, id_pays, infos) values ('Berge and Sons', 2, 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into editeur (nom, id_pays, infos) values ('Klein, Satterfield and Abernathy', 5, null);
insert into editeur (nom, id_pays, infos) values ('Walsh Inc', 2, null);
insert into editeur (nom, id_pays, infos) values ('Kunde Group', 5, 'Sed vel enim sit amet nunc viverra dapibus.');
insert into editeur (nom, id_pays, infos) values ('Beier-Fisher', 4, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into editeur (nom, id_pays, infos) values ('Hoeger and Sons', 3, null);
insert into editeur (nom, id_pays, infos) values ('Green, Walsh and Hamill', 5, 'Suspendisse potenti.');
insert into editeur (nom, id_pays, infos) values ('Moen and Sons', 1, 'Nullam varius.');
insert into editeur (nom, id_pays, infos) values ('Dach-Boyle', 2, 'Vivamus vestibulum sagittis sapien.');
insert into editeur (nom, id_pays, infos) values ('Hettinger, Schneider and Gorczany', 5, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into editeur (nom, id_pays, infos) values ('Hilll-Haley', 5, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into editeur (nom, id_pays, infos) values ('Bahringer LLC', 1, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.');
insert into editeur (nom, id_pays, infos) values ('Lubowitz-Wilderman', 5, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into editeur (nom, id_pays, infos) values ('Greenfelder Inc', 2, null);
insert into editeur (nom, id_pays, infos) values ('Jast, Walter and Stark', 5, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into editeur (nom, id_pays, infos) values ('Lemke-Balistreri', 2, null);
insert into editeur (nom, id_pays, infos) values ('Wyman and Sons', 3, 'Ut tellus.');
insert into editeur (nom, id_pays, infos) values ('Lesch LLC', 5, 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into editeur (nom, id_pays, infos) values ('Jakubowski Inc', 3, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into editeur (nom, id_pays, infos) values ('Emmerich-Rosenbaum', 1, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into editeur (nom, id_pays, infos) values ('Wiza Group', 2, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into editeur (nom, id_pays, infos) values ('Berge LLC', 4, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
insert into editeur (nom, id_pays, infos) values ('Shields-Ferry', 3, null);
insert into editeur (nom, id_pays, infos) values ('Larkin-Bradtke', 2, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into editeur (nom, id_pays, infos) values ('Tillman, Barton and Berge', 1, 'Suspendisse potenti.');
insert into editeur (nom, id_pays, infos) values ('Heller, Batz and Windler', 4, null);
insert into editeur (nom, id_pays, infos) values ('Franecki, Bergnaum and Friesen', 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
